ElixirCost = {
"archers" : 3,
"giant" : 5,
"minions" : 3,
"goblin cage" : 4,
"goblin gang" : 3,
"goblin hut" : 5,
"goblins" : 2,
"knight" : 3,
"mini pekka" : 4,
"musketeer" : 4,
"spear goblins" : 2,
}


ElixirDecode = {
    "0_elixir" : 0,
    "1_elixir" : 1,
    "2_elixir" : 2,
    "3_elixir" : 3,
    "4_elixir" : 4,
    "5_elixir" : 5,
    "6_elixir" : 6,
    "7_elixir" : 7,
    "8_elixir" : 8,
    "9_elixir" : 9,
    "10_elixir" : 10,
}

TroopSide = {
    "enemy_mini pekka" : "enemy",
    "enemy_goblin cage" : "enemy",
    "enemy_goblin gang" : "enemy",
    "enemy_goblin hut" : "enemy",
    "enemy_goblins" : "enemy",
    "enemy_archers" : "enemy",
    "enemy_knight" : "enemy",
    "enemy_musketeer" : "enemy",
    "enemy_spear goblins" : "enemy",
    "enemy_giant" : "enemy",
    "mini pekka" : "ally",
    "goblin brawler" : "ally",
    "goblin cage" : "ally",
    "goblin gang" : "ally",
    "goblin hut" : "ally",
    "goblins" : "ally",
    "archers" : "ally",
    "knight" : "ally",
    "musketeer" : "ally",
    "spear goblins" : "ally",
    "giant" : "ally",
}

Tower_Side = {
    "left_princess_tower" : "ally",
    "right_princess_tower" : "ally",
    "king_tower" : "ally",
    "enemy_left_princess_tower" : "enemy",
    "enemy_right_princess_tower" : "enemy",
    "enemy_king_tower" : "enemy",
}

Dataset_schema = [
    "slot_1","slot_2","slot_3","slot_4","Elixir",
    "ally_prince_tower_left","ally_prince_tower_right","ally_king_tower",
    "enemy_prince_tower_left","enemy_prince_tower_right","enemy_king_tower",
    "archers_ally","archers_enemy","giant_ally","giant_enemy",
    "minions_ally","minions_enemy","goblin_cage_ally","goblin_cage_enemy",
    "goblin_gang_ally","goblin_gang_enemy","goblin_hut_ally","goblin_hut_enemy",
    "goblins_ally","goblins_enemy","knight_ally","knight_enemy",
    "mini_pekka_ally","mini_pekka_enemy","musketeer_ally","musketeer_enemy",
    "spear_goblins_ally","spear_goblins_enemy",
    "archers_ally_x","archers_ally_y","archers_enemy_x","archers_enemy_y",
    "giant_ally_x","giant_ally_y","giant_enemy_x","giant_enemy_y",
    "minions_ally_x","minions_ally_y","minions_enemy_x","minions_enemy_y",
    "goblin_cage_ally_x","goblin_cage_ally_y","goblin_cage_enemy_x","goblin_cage_enemy_y",
    "goblin_gang_ally_x","goblin_gang_ally_y","goblin_gang_enemy_x","goblin_gang_enemy_y",
    "goblin_hut_ally_x","goblin_hut_ally_y","goblin_hut_enemy_x","goblin_hut_enemy_y",
    "goblins_ally_x","goblins_ally_y","goblins_enemy_x","goblins_enemy_y",
    "knight_ally_x","knight_ally_y","knight_enemy_x","knight_enemy_y",
    "mini_pekka_ally_x","mini_pekka_ally_y","mini_pekka_enemy_x","mini_pekka_enemy_y",
    "musketeer_ally_x","musketeer_ally_y","musketeer_enemy_x","musketeer_enemy_y",
    "spear_goblins_ally_x","spear_goblins_ally_y","spear_goblins_enemy_x","spear_goblins_enemy_y",
    "archers_ally_enemy_archers_d","archers_ally_enemy_giant_d","archers_ally_enemy_minions_d",
    "archers_ally_enemy_goblin_cage_d","archers_ally_enemy_goblin_gang_d","archers_ally_enemy_goblin_hut_d",
    "archers_ally_enemy_goblins_d","archers_ally_enemy_knight_d","archers_ally_enemy_mini_pekka_d",
    "archers_ally_enemy_musketeer_d","archers_ally_enemy_spear_goblins_d",
    "giant_ally_enemy_archers_d","giant_ally_enemy_giant_d","giant_ally_enemy_minions_d",
    "giant_ally_enemy_goblin_cage_d","giant_ally_enemy_goblin_gang_d","giant_ally_enemy_goblin_hut_d",
    "giant_ally_enemy_goblins_d","giant_ally_enemy_knight_d","giant_ally_enemy_mini_pekka_d",
    "giant_ally_enemy_musketeer_d","giant_ally_enemy_spear_goblins_d",
    "minions_ally_enemy_archers_d","minions_ally_enemy_giant_d","minions_ally_enemy_minions_d",
    "minions_ally_enemy_goblin_cage_d","minions_ally_enemy_goblin_gang_d","minions_ally_enemy_goblin_hut_d",
    "minions_ally_enemy_goblins_d","minions_ally_enemy_knight_d","minions_ally_enemy_mini_pekka_d",
    "minions_ally_enemy_musketeer_d","minions_ally_enemy_spear_goblins_d",
    "goblin_cage_ally_enemy_archers_d","goblin_cage_ally_enemy_giant_d","goblin_cage_ally_enemy_minions_d",
    "goblin_cage_ally_enemy_goblin_cage_d","goblin_cage_ally_enemy_goblin_gang_d","goblin_cage_ally_enemy_goblin_hut_d",
    "goblin_cage_ally_enemy_goblins_d","goblin_cage_ally_enemy_knight_d","goblin_cage_ally_enemy_mini_pekka_d",
    "goblin_cage_ally_enemy_musketeer_d","goblin_cage_ally_enemy_spear_goblins_d",
    "goblin_gang_ally_enemy_archers_d","goblin_gang_ally_enemy_giant_d","goblin_gang_ally_enemy_minions_d",
    "goblin_gang_ally_enemy_goblin_cage_d","goblin_gang_ally_enemy_goblin_gang_d","goblin_gang_ally_enemy_goblin_hut_d",
    "goblin_gang_ally_enemy_goblins_d","goblin_gang_ally_enemy_knight_d","goblin_gang_ally_enemy_mini_pekka_d",
    "goblin_gang_ally_enemy_musketeer_d","goblin_gang_ally_enemy_spear_goblins_d",
    "goblin_hut_ally_enemy_archers_d","goblin_hut_ally_enemy_giant_d","goblin_hut_ally_enemy_minions_d",
    "goblin_hut_ally_enemy_goblin_cage_d","goblin_hut_ally_enemy_goblin_gang_d","goblin_hut_ally_enemy_goblin_hut_d",
    "goblin_hut_ally_enemy_goblins_d","goblin_hut_ally_enemy_knight_d","goblin_hut_ally_enemy_mini_pekka_d",
    "goblin_hut_ally_enemy_musketeer_d","goblin_hut_ally_enemy_spear_goblins_d",
    "goblins_ally_enemy_archers_d","goblins_ally_enemy_giant_d","goblins_ally_enemy_minions_d",
    "goblins_ally_enemy_goblin_cage_d","goblins_ally_enemy_goblin_gang_d","goblins_ally_enemy_goblin_hut_d",
    "goblins_ally_enemy_goblins_d","goblins_ally_enemy_knight_d","goblins_ally_enemy_mini_pekka_d",
    "goblins_ally_enemy_musketeer_d","goblins_ally_enemy_spear_goblins_d",
    "knight_ally_enemy_archers_d","knight_ally_enemy_giant_d","knight_ally_enemy_minions_d",
    "knight_ally_enemy_goblin_cage_d","knight_ally_enemy_goblin_gang_d","knight_ally_enemy_goblin_hut_d",
    "knight_ally_enemy_goblins_d","knight_ally_enemy_knight_d","knight_ally_enemy_mini_pekka_d",
    "knight_ally_enemy_musketeer_d","knight_ally_enemy_spear_goblins_d",
    "mini_pekka_ally_enemy_archers_d","mini_pekka_ally_enemy_giant_d","mini_pekka_ally_enemy_minions_d",
    "mini_pekka_ally_enemy_goblin_cage_d","mini_pekka_ally_enemy_goblin_gang_d","mini_pekka_ally_enemy_goblin_hut_d",
    "mini_pekka_ally_enemy_goblins_d","mini_pekka_ally_enemy_knight_d","mini_pekka_ally_enemy_mini_pekka_d",
    "mini_pekka_ally_enemy_musketeer_d","mini_pekka_ally_enemy_spear_goblins_d",
    "musketeer_ally_enemy_archers_d","musketeer_ally_enemy_giant_d","musketeer_ally_enemy_minions_d",
    "musketeer_ally_enemy_goblin_cage_d","musketeer_ally_enemy_goblin_gang_d","musketeer_ally_enemy_goblin_hut_d",
    "musketeer_ally_enemy_goblins_d","musketeer_ally_enemy_knight_d","musketeer_ally_enemy_mini_pekka_d",
    "musketeer_ally_enemy_musketeer_d","musketeer_ally_enemy_spear_goblins_d",
    "spear_goblins_ally_enemy_archers_d","spear_goblins_ally_enemy_giant_d","spear_goblins_ally_enemy_minions_d",
    "spear_goblins_ally_enemy_goblin_cage_d","spear_goblins_ally_enemy_goblin_gang_d","spear_goblins_ally_enemy_goblin_hut_d",
    "spear_goblins_ally_enemy_goblins_d","spear_goblins_ally_enemy_knight_d","spear_goblins_ally_enemy_mini_pekka_d",
    "spear_goblins_ally_enemy_musketeer_d","spear_goblins_ally_enemy_spear_goblins_d",
]
